flowchart TD
    A([Will you include code from people outside the project?])
    B([Does non-project code allow re-licensing?])
    C([Does funder require a specific license?])    
    D([Was open source licensing specified in the funding application?])    

    E([Is there a commercial opportunity?])
    F(https://www.sheffield.ac.uk/rs/commercialisation/ice-form)

    G(Use an appropriate open source license.)
    H(Seek assistance from library / RSE.)
    I(Use license stipulated by funder.)

    J([Does the commercial opportunity preclude open source licesning?])

    K(Closed source.)

    A -->|Yes| B
    B -->|No| H
    B -->|Yes| C
    A -->|No| C
    C -->|Yes| I
    C -->|No| D
    D -->|Yes| G
    D --> E
    E -->|Yes| F
    F --> J
    J -->|No| G
    I --> E
    E -->|No| G
    J -->|Yes| K