flowchart LR
    code(Your code) --> commercial(Commercial Licence)
    code --> osl(Open Source Licence)
    code --> usb(Your laptop)
    code --> nowt(Online with no licence)

    commercial --> impact(Impact outside academia)
    osl --> impact

    usb --> sad("😭")
    nowt --> sad

    style sad fontSize:500%;