#name: pages

on: 
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Make docs folders
        run: |
          mkdir docs

      - name: Convert slides - Index
        uses: docker://pandoc/core:latest
        with:
          args: >-  # allows you to break string into multiple lines
            --self-contained   
            -t revealjs
            -V theme=moon
            -o docs/index.html
            index.md